name: GitHub Deployment API
description: Creates GitHub deployment before/after a Buildkite step is executed.
author: https://github.com/ailohq
requirements: []
configuration:
  properties:
    username-env:
      type: string
    token-env:
      type: string
    ref:
      type: string
    environment:
      type: string
    environment_url:
      type: string
    production_environment:
      type: boolean
    transient_environment:
      type: boolean
  additionalProperties: false
