#!/bin/sh

set -euo pipefail

# Curl that will return non-zero exit code,
# but still return its' response if it fails.
# ( https://superuser.com/a/1641410/215321 )
curlf() {
  OUTPUT_FILE=$(mktemp)
  HTTP_CODE=$(curl --silent --output $OUTPUT_FILE --write-out "%{http_code}" "$@")
  if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]] ; then
    >&2 cat $OUTPUT_FILE
    exit 22
  fi
  cat $OUTPUT_FILE
  rm $OUTPUT_FILE
}

USERNAME=$(printenv ${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_USERNAME_ENV:-"GITHUB_USERNAME"})
TOKEN=$(printenv ${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_TOKEN_ENV:-"GITHUB_TOKEN"})
REPO_ORG=$(basename $(dirname $BUILDKITE_REPO) | sed 's/git@github.com://')
REPO_NAME=$(basename $BUILDKITE_REPO .git)

REF=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_REF:-$BUILDKITE_COMMIT}
ENVIRONMENT=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_ENVIRONMENT:-"production"}
ENVIRONMENT_URL=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_ENVIRONMENT_URL:-$(buildkite-agent meta-data get "environment_url" --default "")}
PRODUCTION_ENVIRONMENT=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_PRODUCTION_ENVIRONMENT:-$(
  if [[ $ENVIRONMENT == "prod" || $ENVIRONMENT == "production" ]]; then echo true; else echo false; fi
)}
STATE=$(if [[ $BUILDKITE_COMMAND_EXIT_STATUS == "0" ]]; then echo success; else echo failure; fi)

echo "Finding deployment..."

DEPLOYMENT_ID=$(curlf \
  -u $USERNAME:$TOKEN \
  -H "Accept: application/vnd.github.v3+json" \
  "https://api.github.com/repos/$REPO_ORG/$REPO_NAME/deployments?ref=${REF}&environment=${ENVIRONMENT}&per_page=100" | jq 'first(.[] | select(.payload="buildkite-test-buildkite-build-id").id)')

echo "Deployment found (ID: $DEPLOYMENT_ID)."

echo "Creating deployment status..."

curlf \
  -X POST \
  -u $USERNAME:$TOKEN \
  -H "Accept: application/vnd.github.ant-man-preview+json" \
  https://api.github.com/repos/$REPO_ORG/$REPO_NAME/deployments/${DEPLOYMENT_ID}/statuses \
  -d "{\
    \"state\":\"$STATE\",\
    \"log_url\":\"$BUILDKITE_BUILD_URL\",\
    \"environment\":\"$ENVIRONMENT\",\
    \"environment_url\":\"$ENVIRONMENT_URL\"\
  }"

echo "Deployment status created (state: $STATE)"
