#!/bin/sh

set -euo pipefail

USERNAME=$(printenv ${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_USERNAME_ENV:-"GITHUB_USERNAME"})
TOKEN=$(printenv ${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_TOKEN_ENV:-"GITHUB_TOKEN"})
REPO_ORG=$(basename $(dirname $BUILDKITE_REPO) | sed 's/git@github.com://')
REPO_NAME=$(basename $BUILDKITE_REPO .git)

set -x
ENVIRONMENT=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_ENVIRONMENT:-"production"}
PRODUCTION_ENVIRONMENT=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_PRODUCTION_ENVIRONMENT:-$(
  if [[ $ENVIRONMENT == "prod" || $ENVIRONMENT == "production" ]]; then echo true; else echo false; fi
)}
set +x

echo "Creating Deployment"

DEPLOYMENT_ID=$(curl -s --fail \
  -X POST \
  -u $USERNAME:$TOKEN \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/$REPO_ORG/$REPO_NAME/deployments \
  -d "{\
    \"ref\":\"$BUILDKITE_COMMIT\",\
    \"payload\":\"buildkite-$BUILDKITE_BUILD_ID\",\
    \"environment\":\"$ENVIRONMENT\",\
    \"production_environment\":$PRODUCTION_ENVIRONMENT\
  }" | jq .id)

echo "Deployment created (ID: $DEPLOYMENT_ID)."

curl -s --fail \
  -X POST \
  -u $USERNAME:$TOKEN \
  -H "Accept: application/vnd.github.ant-man-preview+json" \
  https://api.github.com/repos/$REPO_ORG/$REPO_NAME/deployments/${DEPLOYMENT_ID}/statuses \
  -d "{\
    \"state\":\"pending\",\
    \"auto_inactive\":\"false\",\
    \"log_url\":\"$BUILDKITE_BUILD_URL\",\
    \"environment\":\"$ENVIRONMENT\"\
  }"

echo "Deployment status created (state: pending)"