#!/bin/bash

set -euo pipefail

ERROR_CODE=22
# Curl that will return non-zero exit code,
# but still return its' response if it fails.
# ( https://superuser.com/a/1641410/215321 )
curlf() {
  OUTPUT_FILE=$(mktemp)
  HTTP_CODE=$(curl --silent --output $OUTPUT_FILE --write-out "%{http_code}" "$@")
  if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]] ; then
    >&2 cat $OUTPUT_FILE
    echo "Received unexpected HTTP status $HTTP_CODE as response -- checking rate limits"
    curl -si "https://api.github.com/users/$USERNAME" | grep 'x-ratelimit'
    exit $ERROR_CODE
  fi
  cat $OUTPUT_FILE
  rm $OUTPUT_FILE
}

USERNAME=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_USERNAME_ENV:-"GITHUB_USERNAME"}
TOKEN=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_TOKEN_ENV:-"GITHUB_TOKEN"}
REPO_ORG=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_REPOSITORY_ORG:-$(basename $(dirname $BUILDKITE_REPO) | sed 's/git@github.com://')}
REPO_NAME=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_REPOSITORY_NAME:-$(basename $BUILDKITE_REPO .git)}

REF=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_REF:-$BUILDKITE_COMMIT}
ENVIRONMENT=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_ENVIRONMENT:-"production"}
PRODUCTION_ENVIRONMENT=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_PRODUCTION_ENVIRONMENT:-$(
  if [[ $ENVIRONMENT == "prod" || $ENVIRONMENT == "production" ]]; then echo true; else echo false; fi
)}
TRANSIENT_ENVIRONMENT=${BUILDKITE_PLUGIN_GITHUB_DEPLOYMENT_TRANSIENT_ENVIRONMENT:-"false"}

echo "Creating deployment..."

DEPLOYMENT_ID=$(curlf \
  -X POST \
  -u $USERNAME:$TOKEN \
  -H "Accept: application/vnd.github+json" \
  https://api.github.com/repos/$REPO_ORG/$REPO_NAME/deployments \
  -d "{\
    \"ref\":\"$REF\",\
    \"payload\":\"buildkite-$BUILDKITE_BUILD_ID\",\
    \"auto_merge\":false,\
    \"required_contexts\":[],\
    \"environment\":\"$ENVIRONMENT\",\
    \"production_environment\":$PRODUCTION_ENVIRONMENT,\
    \"transient_environment\":$TRANSIENT_ENVIRONMENT\
  }" | jq .id)

echo "Deployment created (ID: $DEPLOYMENT_ID)."

echo "Creating deployment status..."

curlf \
  -X POST \
  -u $USERNAME:$TOKEN \
  -H "Accept: application/vnd.github+json" \
  https://api.github.com/repos/$REPO_ORG/$REPO_NAME/deployments/${DEPLOYMENT_ID}/statuses \
  -d "{\
    \"state\":\"pending\",\
    \"auto_inactive\":\"false\",\
    \"log_url\":\"$BUILDKITE_BUILD_URL\",\
    \"environment\":\"$ENVIRONMENT\"\
  }"

echo "Deployment status created (state: pending)"
